# THIS FILE SHOULD BE MODIFIED BASED ON YOUR CASE

#These variables should be changes
inpath: /Users/mmontes/Documents/computervision/voicerecognition/preprocessed_data/speakers
outpath: /Users/mmontes/Documents/computervision/voicerecognition/results


#Training configuration 
# NOTE: the summation of following sessions must be less than or equal 10 (No clarification about it)
enroll_sessions: 3
test_sessions: 5

#Preprocessing configurations
sampling_rate: 44100
bit_precision: 16
no_channels: 1

#Features configuration (NOTE: to disable a feature, assign it to None)
features:
  - vad #Voice activity detection
  - energy #log-energy
  - cep #cepstral coefficients
  - fb # filter-banks
  #- bnf

cepstral_coefficients: 19
filter_bank: log # filter bank can either be "log" for logarithmic and "lin" for linear 
filter_bank_size: 24
lower_frequency: 300
higher_frequency: 3400
vad: snr #can be either "energy", "snr", "percentil" or "lbl"
snr_ratio: 40 # signal_to_noise ratio
window_size: 0.025 # in seconds (25 milliseconds)
window_shift: 0.010 # in seconds (10 milliseconds)

#UBM configuration
num_gaussians: 64

# i-vectors (tv) configurations (depends on UBM configurations)
batch_size: 30 # size of data batch
tv_rank: 25 # Rank of total variability matrix
tv_interactions: 50 # number of iterations to train the variablity matrix
scoring: cosine # can be either "cosine", or "mahalanobis", or "two_covariance"

#i-vectors (PLDA) configurations (depends on TV configurations)

# Plotting configuration 
DET_curve: rocch # you can choose either 'rocch' or 'steppy'

#Other configuration
